name: Deploy to surge

on:
  push:
    branches:
      - master # Lorsqu'un push advient sur master, on lance le workflow

jobs:
  build-deploy: 
    runs-on: ubuntu-latest
    environment: production
    steps:
  
    # Récupère le code du dépôt Github dans l'environnement du runner
    - name: Checkout
      uses: actions/checkout@v3

    # Installe Node.js version 18
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    # Build the frontend
    - name: Build
      run: |
        npm install
        npm run build
      env:
        # ${{ vars.XXXXX }} se réfère à la variable XXXXX du fichier `.env` à la racine du dépôt
        # Ici, on transmet donc au build les variables d'environnement dont il a besoin
        # ENV_VAR_1 & ENV_VAR_2 ne sont que des exemples, à toi de connaître les bonnes variables nécessaires au build
        ENV_VAR_1: ${{ vars.ENV_VAR_1 }}
        ENV_VAR_2: ${{ vars.ENV_VAR_2 }}

    # Deploy to surge
    - name: Deploy
      # SURGE_DEPLOY_URL et SURGE_TOKEN à configurer dans le fichier `.env` à la racine du dépôt
      # Tu pourras trouver les valeurs dans l'interface surge.sh
      run: | 
        npm install --global surge
        surge  ./dist --domain ${{ vars.SURGE_DEPLOY_URL }} --token ${{ secrets.SURGE_TOKEN }}